# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20170805_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancedate',
            name='hasFreeSeats',
            field=models.BooleanField(default=True),
        ),
    ]
