# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20170807_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancedate',
            old_name='hasFreeSeats',
            new_name='has_free_seats',
        ),
    ]
