# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20170807_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('seatName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('reservation_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
