# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20170820_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.PerformanceDate'),
        ),
    ]
