# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20170820_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_hash',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
    ]
